# Generated by Django 5.2.11 on 2026-03-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_estimated_value_client_billing_cycle_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually'), ('ONE-TIME', 'One-Time')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CREDIT CARD', 'Credit Card'), ('DEBIT CARD', 'Debit Card'), ('BANK TRANSFER', 'Bank Transfer'), ('PAYPAL', 'PayPal'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
