# Generated by Django 5.2.11 on 2026-04-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
    ]
